FROM  --platform=$BUILDPLATFORM node:16-alpine3.17 as build

WORKDIR /app

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn build

FROM marusoftware/openlitespeed:1.7.16-lsphp81

COPY --from=build --chown=nobody:nobody /app/dist /var/www/vhosts/localhost/html