version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
    env_file:
      - .env
  db:
    image: postgres:15.1-bullseye
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres: