version: '3.7'
services:
  server:
    build: .
    stop_signal: SIGINT
    env_file:
      - .env
    depends_on:
      - db
    init: true
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile_production
    ports:
      - 7080:7080
      - 80:80
      - 443:443
         

volumes:
  postgres: