version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
  db:
    image: postgres:15.1-bullseye
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sAOVLIqD344mlugOHzYl
      - POSTGRES_USER=UfqWmq9K3AiKALW9Tas2
      - POSTGRES_DB=marron
volumes:
  postgres: