version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile_production
    stop_signal: SIGINT
    env_file:
      - .env
    depends_on:
      - db
    init: true
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres: