version: '3.7'
services:
  server:
    build: .
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
      - ./migrations:/usr/src/app/migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    init: true
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      interval: 2s
      timeout: 5s
      retries: 5
  client:
    build: ./client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app
    init: true

volumes:
  postgres: