version: '3'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app/server
      - ./migrations:/usr/src/app/migrations
    env_file:
      - .env
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgre
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres: