version: '3.7'
services:
  server:
    image: marusoftware/marron:latest
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    init: true
  db:
    image: marusoftware/postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres: