/* tslint:disable */
/* eslint-disable */
/**
 * Marron API
 * API of Marron
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Idea
 */
export interface Idea {
    /**
     * 
     * @type {string}
     * @memberof Idea
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Idea
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Idea
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Idea
     */
    projectId: string;
}

/**
 * Check if a given object implements the Idea interface.
 */
export function instanceOfIdea(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function IdeaFromJSON(json: any): Idea {
    return IdeaFromJSONTyped(json, false);
}

export function IdeaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Idea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'projectId': json['project_id'],
    };
}

export function IdeaToJSON(value?: Idea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'project_id': value.projectId,
    };
}

