/* tslint:disable */
/* eslint-disable */
/**
 * Marron API
 * API of Marron
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdeaUpdate
 */
export interface IdeaUpdate {
    /**
     * 
     * @type {string}
     * @memberof IdeaUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaUpdate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaUpdate
     */
    projectId?: string;
}

/**
 * Check if a given object implements the IdeaUpdate interface.
 */
export function instanceOfIdeaUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdeaUpdateFromJSON(json: any): IdeaUpdate {
    return IdeaUpdateFromJSONTyped(json, false);
}

export function IdeaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'projectId': !exists(json, 'project_id') ? undefined : json['project_id'],
    };
}

export function IdeaUpdateToJSON(value?: IdeaUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'project_id': value.projectId,
    };
}

