/* tslint:disable */
/* eslint-disable */
/**
 * Marron API
 * API of Marron
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdeaCreate
 */
export interface IdeaCreate {
    /**
     * 
     * @type {string}
     * @memberof IdeaCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaCreate
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaCreate
     */
    projectId: string;
}

/**
 * Check if a given object implements the IdeaCreate interface.
 */
export function instanceOfIdeaCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function IdeaCreateFromJSON(json: any): IdeaCreate {
    return IdeaCreateFromJSONTyped(json, false);
}

export function IdeaCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'projectId': json['project_id'],
    };
}

export function IdeaCreateToJSON(value?: IdeaCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'project_id': value.projectId,
    };
}

