/* tslint:disable */
/* eslint-disable */
/**
 * Marron API
 * API of Marron
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationCreate
 */
export interface OrganizationCreate {
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationCreate
     */
    description: string;
}

/**
 * Check if a given object implements the OrganizationCreate interface.
 */
export function instanceOfOrganizationCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function OrganizationCreateFromJSON(json: any): OrganizationCreate {
    return OrganizationCreateFromJSONTyped(json, false);
}

export function OrganizationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function OrganizationCreateToJSON(value?: OrganizationCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

