/* tslint:disable */
/* eslint-disable */
/**
 * Marron API
 * API of Marron
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OTPCreate
 */
export interface OTPCreate {
    /**
     * 
     * @type {string}
     * @memberof OTPCreate
     */
    otpUrl: string;
    /**
     * 
     * @type {string}
     * @memberof OTPCreate
     */
    otpRecovery: string;
}

/**
 * Check if a given object implements the OTPCreate interface.
 */
export function instanceOfOTPCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "otpUrl" in value;
    isInstance = isInstance && "otpRecovery" in value;

    return isInstance;
}

export function OTPCreateFromJSON(json: any): OTPCreate {
    return OTPCreateFromJSONTyped(json, false);
}

export function OTPCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): OTPCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'otpUrl': json['otp_url'],
        'otpRecovery': json['otp_recovery'],
    };
}

export function OTPCreateToJSON(value?: OTPCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'otp_url': value.otpUrl,
        'otp_recovery': value.otpRecovery,
    };
}

